### ISSUE TITLE
New ultrasonic sensors

### ISSUE THREAD

**Issue by SohaibAl-emara** [CapstoneAOV/DevTasks#7]
Did we order it yet? what board are we using to read the data?
Any Updates regarding that?

**Comment by SohaibAl-emara** [comment]
@mahmom3  Research accurate and reliable ultrasonics. Not the typical arduino modules.

**Comment by anoop54** [comment]
Hey Sohaib can you help with the research. I want to make sure what we get is actually used in the system. So we need accurate distance, and wide range of reading. Options are as follows:

- https://www.digikey.ca/product-detail/en/maxbotix-inc/MB1010-000/1863-1002-ND/7896774
       - They have various versions, MB1040-000, MB1000-000 and the  one linked, let's compare

- https://www.amazon.ca/KeeYees-Integrated-Ultrasonic-Waterproof-Transducer/dp/B07V6HSN8B/ref=sr_1_5?keywords=ultrasonic+sensor&qid=1584747336&sr=8-5

Let's try to place order as soon as possible.

**Comment by mahmom3** [comment]
I think these two can work as well:
- https://www.robotshop.com/ca/en/dfrobot-urm-v50-ultrasonic-sensor.html?gclid=CjwKCAjwguzzBRBiEiwAgU0FT5qR5URq2WsZdVy9jXzI2i75E0jak9s2GLoak1LjMU497XHjEnbm6xoCOxQQAvD_BwE
- https://www.dfrobot.com/product-1505.html?gclid=CjwKCAjwguzzBRBiEiwAgU0FT8H76A6S3ckX-yv1r7SRo8fXSBwK7KeC9oCh1R9flQDaFn6a6HsqshoC-6gQAvD_BwE

Second Link has option for 3-5 days shipment
Please let me know what you decide on
